### PR TITLE
Add a constructor for Context class and enhance storage phpdoc

### PR DESCRIPTION
**Pull request by snoob**
Hello.

When you want to pass variables to constraint check you have to write several lines. 
I suggest to add a constructor on Context class to simplify it.

WDYT ?

### CODE REVIEW

**Comment by migo315** [comment]
Looks good - thanks. :-)

**Comment by migo315** [comment]
@snoob The initialization with empty array is still required because the constructor does not set the property (but uses the `add` function). Can you add this to pass the tests?

`private $storage = [];`

**Comment by snoob** [comment]
oh yes sorry 

If you prefer i can set storage directly without using **add** ? as the current "business" rule (key already exists) can't be triggered from the constructor but it depends if you plan to implement more checks in the future. 

For example, only allows **isActive** method to add **_feature** key and forbid it in the **add** method 

```
 public function __construct(array $storage = [])
  {
        $this->storage = $storage
  }
``` 
    
Tell me

**Comment by migo315** [comment]
I would prefer to use the `add` method, so that we could add more checks later. :-)

**Comment by snoob** [comment]
Repushed sorry for the delay :)

**Comment by snoob** [comment]
I added a short description for the constructor because the CI failed

**Comment by migo315** [comment]
phpcs seems to fail. But I will merge it and fix that later. Thanks for your contribution. 👍

**Comment by snoob** [comment]
You are welcome thank you for your reactivity. I fixed the short description and others problems can be resolved automatically

**Pull request merged**
